import { Info } from "lucide-react";
import { SYSTEM_PROMPT } from "../../../../server/utils/bible-study-utils";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "../../../ui/hover-card";
import { Separator } from "../../../ui/separator";

export default function BibleStudyNoteUnderstandingHoverCard() {
  return (
    <HoverCard openDelay={0}>
      <HoverCardTrigger asChild>
        <Info size={16} className="shrink-0" />
      </HoverCardTrigger>
      <HoverCardContent align="center" className="w-full max-w-xl">
        <div className="flex flex-col gap-4 text-xs">
          <p className="text-sm font-medium">About the Understand Note</p>
          <p className="text-muted-foreground">
            Lumen uses AI to help you understand the Bible.
          </p>
          <Separator />
          <p className="text-muted-foreground">
            We are specifically using the{" "}
            <a
              target="_blank"
              href="https://platform.openai.com/docs/models/gpt-4o"
              className="text-blue-500 underline"
            >
              Open AI GPT-4o
            </a>{" "}
            model to generate responses.
          </p>
          <p className="text-muted-foreground">
            The AI has been given the following instructions:
          </p>
          <p className="whitespace-pre-wrap rounded-md bg-muted p-2">
            {SYSTEM_PROMPT}
          </p>
          <Separator />
          <p className="text-muted-foreground">
            Since the responses are generated by AI, they may not always be
            accurate. Always compare responses with scripture and consult
            trusted sources for deeper understanding.
          </p>
        </div>
      </HoverCardContent>
    </HoverCard>
  );
}
